spring.application.name=trocenchaires
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databasename=trocenchaires;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$word

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.messages.encoding=UTF-8
spring.web.locale=en
app.jwt.secret=WPjiQ7BrqDSO11j3A6pM60RMhgIA7OW3